### ISSUE TITLE
openScale:1124: error: 'LOCATION_TRIGGER_CHARACTER' was not declared in this scope    EEPROM.write(LOCATION_TRIGGER_CHARACTER, setting_trigger_character);

### ISSUE THREAD

**Issue by janterlaak** [sparkfun/OpenScale#13]
compile error, need openscale.h a update?

**Comment by kevinjos** [comment]
I'm not sure if it's safe, but it compiles and runs well enough: https://github.com/sparkfun/OpenScale/pull/14

**Comment by ADataDate** [comment]
Branch v04 has the most up to date Arduino sketch and header file. It will be merged with master once the merge conflicts get resolved.

**Comment by kevinjos** [comment]
The PR I issued fixes the compile error noted above. What are your thoughts on merging it while resolving the v04 branch merge conflicts such that the master branch compiles in the mean time? If that doesn't sound good, how about making a note on the README.md of the master branch pointing users to branch v04?
