### ISSUE TITLE
Getting "inf" for weight

### ISSUE THREAD

**Issue by felixgalindo** [sparkfun/OpenScale#16]
Serial Load Cell Converter version 1.0
By SparkFun Electronics
No remote sensor found
Minimum time between reports: 868
Press x to bring up settings
Readings:
1982,inf,lbs,164148,24.31,0,
2850,inf,lbs,164096,24.31,0,
3877,inf,lbs,164174,24.31,0,
5364,inf,lbs,164185,24.31,0,
6850,inf,lbs,164152,24.37,0,
8337,inf,lbs,164218,24.37,0,

**Comment by ADataDate** [comment]
Have you been through the calibration menu yet? If yes, then We'd need to troubleshoot your connections and look at hardware. If no, then enter "x" in the com port to bring up the calibration menu and then enter 1 to tare to zero and then enter 2 to calibrate it.

**Comment by nseidle** [comment]
Closed from inactivity. Please re-open if you still have the issue.
