### ISSUE TITLE
Temp and Humidity

### ISSUE THREAD

**Issue by dapug** [sparkfun/OpenScale#17]
Your Make article mentions the HTU21D, but in the schematic here I only see a place to hook up a DS18B20.  Can you explain?

**Comment by ADataDate** [comment]
Openscale does not use the HTU21D. It relies on an on-board temperature sensor (TMP-102) as well as the external, waterproof DS18B20 temp sensor. The Make article came out before the Openscale design was finished and used different sensors.

**Comment by dapug** [comment]
Thanks, this is what I suspected.  So basically, measuring humidity is a non-goal for the project.  Just wanted to confirm.  I can see value either way.
