### ISSUE TITLE
Adding Wifi

### ISSUE THREAD

**Issue by dapug** [sparkfun/OpenScale#18]
It looks like all communication is serial, so I assume if you want it connected on wifi (via ESP-x of choice) then that would be done with a serial connection to pipe the data to an ESP8266/32 device, and the ESP then relays that to a server destination of choice (via REST or HTTP or MQTT or whatever).  

Since ESP-01/12/32 is not built into OpenScale, shouldn't there be a simple UART connection for it externally, and/or a way to bypass the built in FT231?  Or am I way off in the weeds here with a non-scenario for OpenScale?

**Comment by ADataDate** [comment]
Openscale has a UART connection (next to the USB labeled "Serial Out") specifically for connecting external serial devices (like OpenLog). Is that what you were asking?

**Comment by nseidle** [comment]
Closed due to lack of activity. Please reopen if you have any questions. ADataDate is spot on. You can add wifi pretty easily through the UART connection.
