### ISSUE TITLE
Readings wrong from third reading. And _always_ from third one.

### ISSUE THREAD

**Issue by kramer65** [sparkfun/OpenScale#20]
I'm having massive trouble with my OpenScale. I've tarred it to zero and calibrated it with a one kilogram weight. After that I exit the calibration program and exit the menu to get the readings. In the meantime I do not remove the one kilogram weight. After exiting the menu, the first two readings are correct, but the third one is wrong (see the readings below this message). The weird thing is that it's always the third reading. I've repeated it about 20 times, and it's without exception, _always_ the third one. 

When I go back into calibration after this (and I don't touch the weight), it again reports 1 kg in the calibration again. In summary, it always works well in the calibration program, but after exiting, the values are wrong starting from the third value.

Does anybody know what could be wrong here?

```
Reading: [1.0174 kg]   Calibration Factor: -11746
Reading: [1.0158 kg]   Calibration Factor: -11746
Reading: [1.0172 kg]   Calibration Factor: -11746
Reading: [1.0151 kg]   Calibration Factor: -11746

Serial Load Cell Converter version 1.0
By SparkFun Electronics
No remote sensor found
System Configuration
1) Tare scale to zero [-23519]
2) Calibrate scale [-11746]
3) Timestamp [On]
4) Set report rate [711]
5) Set baud rate [9600 bps]
6) Change units of measure [kg]
7) Decimals [2]
8) Average amount [4]
9) Local temp [Off]
r) Remote temp [Off]
s) Status LED [Blink]
t) Serial trigger [Off]
q) Raw reading [On]
c) Trigger character: [48]
x) Exit
>Exiting
152222,1.02,kg,-32345,   # the first two are correct
152933,1.02,kg,-32334,
153916,0.06,kg,-32331,   # from here it's wrong
155351,0.04,kg,-32317,
156785,0.03,kg,-32300,
158220,0.04,kg,-32323,
159654,0.04,kg,-32311,
161088,0.04,kg,-32327,
162523,0.04,kg,-32368,
```

**Comment by kramer65** [comment]
Ok, after messing with the settings I now have it working. No idea why though, since I set everything back to how it was in in the settings I posted above.

So my only advice to anyone reading this: mess with the settings.. :S

**Comment by nayanagg** [comment]
Hi, @kramer65 I'm facing the exact issue which you have mentioned above. Kindly let me know how to correct this mess.  Early reply is much appreciated!
Cheers!!
