### ISSUE TITLE
OpenScale doesn't remember zero point after powering down and up again

### ISSUE THREAD

**Issue by kramer65** [sparkfun/OpenScale#21]
I've got the OpenScale attached to my Raspi, which after some [initial](https://github.com/sparkfun/OpenScale/issues/19) [trouble](https://github.com/sparkfun/OpenScale/issues/20) now works fine. The only problem I now still have is that it doesn't remember the zero point between reboots of the Raspberry Pi. The calibration is stored correctly between power downs (`-9649`), but the zero point (now `-23859`) is constantly forgotten and reset to `8647409`.

For this reason I need to tar to zero after every reboot which is absolutely annoying. 

Does anybody know why it doesn't remember the zero point and how I can solve this? Another solution would be if I could set the zero point using Python so that I can simply set it in the beginning of the script which reads out the measurements.

All tips are welcome!

**Comment by ADataDate** [comment]
Yes - There is an updated version of the firmware here: https://github.com/sparkfun/OpenScale/blob/master/firmware/OpenScale/OpenScale/OpenScale.ino which solves that problem. 

Sorry Openscale has put you through such a crucible. I did look into your-every third weight-problem but I wasn't able to reproduce it. If you have any more questions open another issue - I'm watching this a little more closely now.

**Comment by kramer65** [comment]
Hi @ADataDate - Thanks for the response and the suggestion. Good to hear there are things moving with the OpenScale. I'm kinda lost with that link though. Any idea how I can load that firmware onto the OpenScale board from a raspi?

**Comment by asachs01** [comment]
@kramer65 @ADataDate +1 to this. I've not been able to find a method for flashing the updated firmware to the openscale.

**Comment by nseidle** [comment]
Hi @kramer65 @asachs01 @nayanagg - This is a bit old but to answer the original question: The INO file is an Arduino sketch that can be compiled and uploaded to OpenLog via the Arduino IDE (no other tools required). [Here's](https://learn.sparkfun.com/tutorials/installing-arduino-ide/all) a tutorial to get you started.

You can download the entire repo [here](https://github.com/sparkfun/OpenScale/archive/master.zip). The INO that you will need to open in Arduino is in the firmware/OpenScale directory.

I've fixed a handle of large and small bugs in v1.2. If you get the chance, please try out the new firmware. I welcome your feedback.

**Comment by nseidle** [comment]
There's additional info about upgrading the firmware [here](https://learn.sparkfun.com/tutorials/openscale-applications-and-hookup-guide?#upgrading-the-firmware).
