### ISSUE TITLE
System config menu appears multiple times

### ISSUE THREAD

**Issue by Thurgs** [sparkfun/OpenScale#22]
Sorry, I am quite new to this (and loving it so far).
I have been using the OpenScale from Sparkfun and also some Arduino Pro Minis, but the new ones seem to have something strange happening where if I enter multiple characters at one time (such as 'x1x') it just prints the menu 3 times in a row. It appears to just read the first character and just use this in the place of each of the characters. If I print 'xxxx' it will just open the menu 4 times. 
In the OpenScale and the older Pro Minis, I could send 'x1x' all at once and it will enter the menu, Tare the scale and then exit the menu. This is what I would like to do for my application.

I have reloaded the code and put it onto the old and new devices and it seems that the new Pro Minis are always having this issue where the older ones and the OpenScale device do not. 

Would really appreciate any help and guidance.

**Comment by nseidle** [comment]
Yup. This was really annoying. Sorry it took so long to fix but it's good to go in v1.2. I've fixed a handful of large and small bugs in v1.2. If you get the chance, please try out the new firmware. I welcome your feedback.
