### ISSUE TITLE
Negative number reported for weight

### ISSUE THREAD

**Issue by adrienhobbs** [sparkfun/OpenScale#23]
After calibrating, weight is being reported back as a negative number. Any ideas what could be causing this?

**Comment by ADataDate** [comment]
What weight did you use to calibrate? I have found that trying to calibrate with a zero weight produces this result.

**Comment by adrienhobbs** [comment]
We used a 25 pound weight to calibrate with. First we tared the scale, and then calibrated with the weight.

**Comment by adrienhobbs** [comment]
Is it normal to have a negative number for the calibration? Using a negative number seems to fix the problem.

**Comment by nseidle** [comment]
I'm sorry it took so long to respond: It is possible to have a negative number.

Once you tare the scale, and then calibrate it, then remove the calibration weight I have seen some rare instances where the output is -0.002 for example.

If you're still having problems please open a new issue. I just pushed v1.2 of OpenScale which should fix a variety of small bugs and annoyances.
