### ISSUE TITLE
cannot load new firmware

### ISSUE THREAD

**Issue by MIKMAI** [sparkfun/OpenScale#29]
I tried to load firmware according to instructions on openscale page but all i get is "no matching function for HX711" (i think i got the libraries right)
 I followed instructions described on openscale page but still don't manage to get it work. 
I'm not familiar with coding so much that i could find the problem from the code right away.
Just need openscale for hobby project.

**Comment by nseidle** [comment]
Please post the errors from the Arduino IDE if possible. "No matching function for HX711" sounds like a library issue. Be sure to grab the latest from https://github.com/bogde/HX711

**Comment by MIKMAI** [comment]
Yes it is probably some error with the library. I used links on openscale instructions page. Thanks I'll try that link also.

The error message is:
![image](https://user-images.githubusercontent.com/47990756/53433553-45ad3880-39fd-11e9-8446-b8d76b2b01c6.png)

Instructions page:
https://learn.sparkfun.com/tutorials/openscale-applications-and-hookup-guide?_ga=2.52282158.660258565.1551122233-1048845638.1550911326#upgrading-the-firmware

**Comment by nseidle** [comment]
Fooey. Looks like @bogde may have changed how the library works and broken existing sketches.

Checkout their new example [here](https://github.com/bogde/HX711/blob/master/examples/HX711_basic_example/HX711_basic_example.ino).

I suspect you will need to change a few lines of OpenScale:

    HX711 scale;

and in setup add:

    scale.begin(DAT, CLK);

I don't have hardware available atm but will update firmware in the coming days.

**Comment by nseidle** [comment]
I pushed a new version. Please kick the tires and let me know if you still have issues. The changes I made simply make the code compile, no function changes.
