### ISSUE TITLE
The readsystemsettings() routine is missing from OpenScale.ino

### ISSUE THREAD

**Issue by AaronBAllen** [sparkfun/OpenScale#30]
I downloaded this and found that I did not have two of the .h files.  That was easy to remedy, the lack of this internal subroutine is more difficult to remedy.  Can I go get it from an earlier version of this software?

**Comment by AaronBAllen** [comment]
I found the commands in the other files which must reside in the same directory.  I am unable to compile anyway because the compiler does not recognize all of the features of HX711.h

**Comment by nseidle** [comment]
Be sure to pull down the entire repo and open the OpenScale.ino from the Arduino IDE. It will open the various files including the System.ino file that contains the readSystemSettings() function.

You'll need to install the HX711 library from Bogdan. This is documented in the [hookup guide](https://learn.sparkfun.com/tutorials/openscale-applications-and-hookup-guide/all#upgrading-the-firmware). They have also recently packaged the lib so you can now install it from the Arduino library manager by search 'HX711'.
