### ISSUE TITLE
Actual v04 Checklist Review

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/OpenScale#8]
1) some nets are not drawn straight out one grid space from the pin: J2, R12, R11

2) got some over sized nets around the FT chip (> 0.006")

3) I would like to see a jumper diagram for the 3-way jumper, otherwise I think the description needs some cleaning up

4) BOM:
- 470pf on BOM not in design 
- 4 x 10K in design but only 2 on BOM
- Push Button in design and on BOM are different 
- TRANS-11151 not on BOM

5) board dimension thickness is 0.1" instead of 0.08"

6) there are both 0.02" vias and 0.015" vias in the design (didn't look intentional)

7) C4 has an unnecessary bridge to GND (just looks kind of funny)

8) the trace-nubs at the end of the pads on the USB look like they were intentionally placed there, is this for AOI inspection?

9) This is knit-picky, but there are a few traces that either enter a pad at an angle or do not enter the pad at the pad's center point. Some of the mentioned instances are in tightly spaced areas, but some are not. Might be worth trying to clean up some of the instances that have some extra space around them. (optional)

10) TMP102 does not appear to have tNAME or tVALUE elements in the BRD

11) Looks like the bottom-side labels for JP1 (the 3 x 1 Temp header) are no longer lined up with the through-holes

12) Not sure if the upper two standoffs were intentionally placed out from the corner of the board, but I thought it worth mentioning if this was unintentional.

**Comment by ADataDate** [comment]
Board and Schematic files updated.

**Comment by ericorosel** [comment]
Issues all resolved, closing!
